USE MASTER;
GO

CREATE DATABASE BD_DESARROLLO
ON PRIMARY
(NAME='DESARROLLO', FILENAME='C:\BaseDatos\DESARROLLO.mdf', SIZE=200MB, MAXSIZE=5000MB, FILEGROWTH=25%)
LOG ON
(NAME='DESARROLLO_LOG', FILENAME='C:\BaseDatos\DESARROLLO_LOG.ldf', SIZE=100MB, MAXSIZE=1000MB, FILEGROWTH=25%)
GO

USE BD_DESARROLLO;
GO

CREATE SCHEMA VISMED;
GO